### PR TITLE
fix #704 - vanilla items cannot be renamed

### LINKED ISSUE #704: [BUG] Anvil repairing does not work for vanilla (non-mythic) items [MD 8.4.2]
Anvil for MD items work as intended, but when I, for example, put damaged vanilla bow into it and I want to repair it with another bow, the anvil output shows repaired bow for 0.1 sec and then disappears.

## Steps to Reproduce
1. create a clean paper server (Paper version git-Paper-307 (MC: 1.19.2))
2. put only some basic plugins in the plugins folder (I am using CMI, ItemsAdder, MythicDrops, LuckPerms)
3. try to repair some vanilla (non-mythic item) in the anvil - it wont work
4. When you remove MythicDrops.jar from the plugins folder and restart the server, anvil works.

## Your Environment
MD 8.4.2
Paper version git-Paper-307 (MC: 1.19.2)
[config.txt](https://github.com/MythicDrops/MythicDrops/files/10801388/config.txt)

### PR DESCRIPTION
**Pull request by KodingDev**
This fixes issue #704, where the display names of non-renamed items can be a blank string, instead of null. When paired with the default config, especially for the `socketExtender`, which has a blank display name, this causes the anvil to be unusable for vanilla items. We can resolve this by checking for a blank string, and ignoring it.

### CODE REVIEW

File: src/main/kotlin/com/tealcube/minecraft/bukkit/mythicdrops/inventories/AnvilListener.kt [hunk 1]
```diff
@@ -52,8 +53,7 @@ internal class AnvilListener(
     }
 
     private fun handleEarlySocketExtenderCheck(event: PrepareAnvilEvent) {
-        val anyAreSocketExtenders = event.inventory.contents.filterNotNull()
-            .any { it.displayName == settingsManager.socketingSettings.items.socketExtender.name.chatColorize() }
+        val anyAreSocketExtenders = event.inventory.anyDisplayName(settingsManager.socketingSettings.items.socketExtender.name.chatColorize())
```
Comment (ToppleTheNun) [inline src/main/kotlin/com/tealcube/minecraft/bukkit/mythicdrops/inventories/AnvilListener.kt:56]: There's a slightly different fix required for this, which is to use the `SocketExtenderTypeManager` and compare against all of the known `SocketExtenderType`s.

Comment (ToppleTheNun) [reply src/main/kotlin/com/tealcube/minecraft/bukkit/mythicdrops/inventories/AnvilListener.kt:56]: That would ultimately end up in something like the below:
```kotlin
val anyAreSocketExtenders = socketExtenderTypeManager.get().any { socketExtenderType ->
  event.inventory.anyDisplayName(socketExtenderType.socketExtenderStyleChatColorized)
}
```
